/* PREDICAR AUTOMOTIVE PERU SAC
   Los tres idiomas y la funcion que elige el texto.
   Orden de carga: config, idiomas, datos, app, agenda. */

var L = 0, LANGS = ["es","en","de"];

var T = {
"nav.casos":["Casos reales","Real cases","Echte Fälle"],
"nav.peritaje":["Cómo es el peritaje","How the inspection works","Ablauf des Gutachtens"],
"nav.servicios":["Servicios","Services","Leistungen"],
"nav.proceso":["Cómo es el proceso","How the process works","So läuft es ab"],
"nav.agendar":["Agendar cita","Book a slot","Termin buchen"],
"nav.sistema":["Acceso al sistema","System login","System-Login"],

"hero.eyebrow":["Peritaje automotriz · Lima, Perú","Vehicle inspection · Lima, Peru","Kfz-Gutachten · Lima, Peru"],
"hero.h1a":["Entérate exactamente qué estás comprando","Know exactly what you are buying","Wisse genau, was du kaufst"],
"hero.h1b":["antes de firmar.","before you sign.","bevor du unterschreibst."],
"hero.sub":["Peritaje de ingeniería para autos seminuevos. Medimos, documentamos y te decimos si conviene comprar, negociar o retirarte.","Engineering-grade inspection for used cars. We measure, we document, and we tell you whether to buy, negotiate or walk away.","Ingenieurmäßige Begutachtung von Gebrauchtwagen. Wir messen, dokumentieren und sagen dir, ob du kaufen, verhandeln oder aussteigen solltest."],
"hero.cta1":["Ver 9 casos reales","See 9 real cases","9 echte Fälle ansehen"],
"trust.1t":["+300 clientes satisfechos","+300 satisfied clients","+300 zufriedene Kunden"],
"trust.1d":["Y un solo auto revisado en promedio, no tres","And one car inspected on average, not three","Und ein geprüftes Auto im Schnitt, nicht drei"],
"trust.2t":["Informe el mismo día","Same-day report","Bericht am selben Tag"],
"trust.2d":["PDF con fotos, hallazgos y costos reales","PDF with photos, findings and real costs","PDF mit Fotos, Befunden und realen Kosten"],
"trust.3t":["Ingeniería, no opinión","Engineering, not opinion","Technik statt Meinung"],
"trust.3d":["Ingeniero mecatrónico a cargo del peritaje","A mechatronics engineer runs the inspection","Ein Mechatronik-Ingenieur führt die Prüfung durch"],

"scan.title":["Escáner OBD-II","OBD-II scanner","OBD-II-Scanner"],
"scan.live":["CONECTADO","CONNECTED","VERBUNDEN"],
"scan.rep":["Reparaciones necesarias","Repairs needed","Nötige Reparaturen"],
"scan.neg":["Margen de negociación","Negotiation margin","Verhandlungsspielraum"],
"scan.note":["Ejemplo ilustrativo de un informe Predicar","Illustrative example of a Predicar report","Beispielhafte Darstellung eines Predicar-Berichts"],

"via.otra":["¿Y si era lo otro?","Looking for the other one?","Doch das andere?"],"via.abroker":["Ver el servicio de broker: yo te busco el auto →","See the sourcing service: I find the car for you →","Zur Fahrzeugsuche: ich finde das Auto für dich →"],"via.aperitaje":["Ver el peritaje: reviso el auto que ya elegiste →","See the inspection: I check the car you already chose →","Zum Gutachten: ich prüfe dein gewähltes Auto →"],"pre.eyebrow":["Un dato más","One more thing","Noch eine Sache"],"pre.h2":["¿Cuál es tu presupuesto?","What is your budget?","Wie hoch ist dein Budget?"],"pre.sub":["Según el rango cambia lo que se puede negociar y los casos que te sirven de referencia.","The range changes what can be negotiated and which cases are relevant to you.","Die Spanne bestimmt, was verhandelbar ist und welche Fälle für dich relevant sind."],"pre.neg":["En ese rango hemos llegado a negociar","In that range we have negotiated up to","In dieser Spanne haben wir verhandelt bis zu"],"pre.o1k":["Salida 1","Option 1","Weg 1"],"pre.o1":["Negociar el precio con los hallazgos en la mano. Cada problema tiene su costo de reparación, y ese costo es tu argumento.","Negotiate the price with the findings in hand. Every problem has a repair cost, and that cost is your argument.","Den Preis mit den Befunden in der Hand verhandeln. Jeder Mangel hat seine Reparaturkosten — das ist dein Argument."],"pre.o2k":["Salida 2","Option 2","Weg 2"],"pre.o2":["Retirarte. Si el auto tiene demasiados problemas, el mejor negocio es el que no se hace. Te lo digo con números, no con corazonadas.","Walk away. If the car has too many problems, the best deal is the one you don't make. I tell you with numbers, not hunches.","Aussteigen. Bei zu vielen Mängeln ist der beste Deal der, den man nicht macht. Ich sage es dir mit Zahlen, nicht aus dem Bauch."],"pre.sim":["Parecido a tu presupuesto","Close to your budget","Nah an deinem Budget"],"pre.brk":["Estos casos son los más parecidos a tu presupuesto: {n}. Los demás quedan abajo.","These are the closest to your budget: {n}. The rest are below.","Diese liegen deinem Budget am nächsten: {n}. Der Rest steht darunter."],"pre.brk0":["Todavía no he cerrado un caso exactamente en ese rango. Estos son los que tengo, y en la reserva me cuentas qué buscas.","I have not closed a case exactly in that range yet. These are the ones I have — tell me what you are after when you book.","In dieser Spanne habe ich noch keinen Fall. Das sind meine Fälle — sag mir bei der Buchung, was du suchst."],"pre.cta":["Agendar mi peritaje","Book my inspection","Gutachten buchen"],"nav.sugerencia":["Qué carro te conviene","Which car suits you","Welches Auto passt"],"sug.eyebrow":["El mercado, no mi opinión","The market, not my opinion","Der Markt, nicht meine Meinung"],"sug.h2":["¿Qué carro me sugieres?","Which car should I get?","Welches Auto soll ich nehmen?"],"sug.sub":["Esto es lo que de verdad se transfiere en Perú. Datos de SUNARP, no impresiones mías.","This is what actually changes hands in Peru. SUNARP data, not my impressions.","Das wechselt in Peru wirklich den Besitzer. SUNARP-Daten, nicht meine Eindrücke."],"sug.alta":["Alta gama","Premium brands","Oberklasse"],"sug.media":["Gama media","Mainstream brands","Mittelklasse"],"sug.cMarca":["Marca","Brand","Marke"],"sug.cTransf":["Transferencias acumuladas · enero a junio 2026","Transfers accumulated · January to June 2026","Übertragungen kumuliert · Januar bis Juni 2026"],"sug.cProm":["Promedio al mes","Monthly average","Schnitt pro Monat"],"sug.cVar":["vs. 2025","vs. 2025","vs. 2025"],"sug.cCuota":["Cuota","Share","Anteil"],"sug.pie":["Cómo leerlo","How to read it","So liest du das"],"sug.leyalta":["De las cuatro, {marca} es la que más creció: {v}% frente al {mv}% del mercado. Más transferencias significan más repuestos, más talleres que la conocen y una reventa más fácil. Sobre {total} transferencias en total, enero a junio de 2026.","Of the four, {marca} grew the most: {v}% against the market {mv}%. More transfers mean more parts, more workshops that know it, and an easier resale. Out of {total} transfers, January to June 2026.","Von den vieren wuchs {marca} am stärksten: {v}% gegenüber {mv}% im Markt. Mehr Übertragungen bedeuten mehr Teile, mehr Werkstätten und leichteren Wiederverkauf. Von {total} Übertragungen, Januar bis Juni 2026."],"sug.leymedia":["Toyota se lleva 28 de cada 100 transferencias del país. Esa es la razón de que su repuesto sea barato y de que cualquier taller la conozca. {marca} es la que más creció este año: {v}%. Sobre {total} transferencias en total, enero a junio de 2026.","Toyota takes 28 of every 100 transfers in the country. That is why its parts are cheap and every workshop knows it. {marca} grew the most this year: {v}%. Out of {total} transfers, January to June 2026.","Toyota macht 28 von 100 Übertragungen aus. Deshalb sind Teile billig und jede Werkstatt kennt sie. {marca} wuchs dieses Jahr am stärksten: {v}%. Von {total} Übertragungen, Januar bis Juni 2026."],"sug.fuente":["Fuente: SUNARP, vía el Informe del Sector Automotor de la AAP (julio 2026)","Source: SUNARP, via the AAP automotive sector report (July 2026)","Quelle: SUNARP, über den AAP-Branchenbericht (Juli 2026)"],"brk.eyebrow":["Broker vehicular","Car sourcing","Fahrzeugsuche"],"brk.h2":["Seis clientes que no salieron a buscar auto","Six clients who never went car hunting","Sechs Kunden, die nie selbst suchen mussten"],"brk.sub":["Me dijeron qué necesitaban y cuánto tenían. Yo busqué, peritié y negocié.","They told me what they needed and what they had. I searched, inspected and negotiated.","Sie sagten mir, was sie brauchten und hatten. Ich suchte, prüfte und verhandelte."],"brk.q":["Qué buscaba","What they wanted","Was gesucht war"],"brk.e":["Qué le conseguí","What I found","Was ich fand"],"cam.q":["¿Ya tienes un auto definido, o quieres que te busque una mejor opción a buen precio?","Already have a car in mind, or would you rather I find you a better one at a good price?","Hast du schon ein Auto im Blick, oder soll ich dir ein besseres zum guten Preis suchen?"],"cam.1k":["Ya tengo el auto","I have the car","Ich habe das Auto"],"cam.1t":["Peritaje automotriz","Vehicle inspection","Fahrzeuggutachten"],"cam.1p":["Lo reviso antes de que firmes: mecánica, escáner de todos los módulos y análisis legal. Te digo si conviene comprar, cuánto pedir de rebaja o cuándo retirarte.","I inspect it before you sign: mechanics, a scan of every module and the legal check. I tell you whether to buy, how much to knock off, or when to walk away.","Ich prüfe es vor der Unterschrift: Mechanik, Scan aller Steuergeräte und Rechtsprüfung. Ich sage dir, ob du kaufen sollst, wie viel Nachlass du forderst oder wann du gehst."],"cam.1c":["Ver cómo es el peritaje →","See how the inspection works →","So läuft das Gutachten →"],"cam.2k":["Todavía lo estoy buscando","Still looking","Ich suche noch"],"cam.2t":["Broker vehicular","Car sourcing","Fahrzeugsuche"],"cam.2p":["Me encargo de todo: lo busco, lo inspecciono y negocio con el vendedor. No te expones a estafas ni pierdes tiempo. Te encuentro la mejor opción al mejor precio, rápido y seguro.","I handle everything: I find it, inspect it and negotiate with the seller. No scams to dodge, no time lost. I get you the best option at the best price — fast and safe.","Ich kümmere mich um alles: suchen, prüfen und mit dem Verkäufer verhandeln. Kein Betrugsrisiko, keine verlorene Zeit. Ich finde dir die beste Option zum besten Preis — schnell und sicher."],"cam.2c":["Ver el servicio de broker →","See the sourcing service →","Zur Fahrzeugsuche →"],"casos.eyebrow":["Prueba, no promesas","Proof, not promises","Beweise statt Versprechen"],
"casos.h2":["Resultados de los últimos clientes","Results from our latest clients","Ergebnisse unserer letzten Kunden"],
"casos.h2brk":["Entregas reales, con nombre y apellido","Real handovers, with names","Echte Übergaben, mit Namen"],"casos.subbrk":["Clientes que me dijeron qué buscaban y a los que les puse el auto en la puerta.","Clients who told me what they wanted and got the car at their door.","Kunden, die mir sagten was sie wollten — und das Auto vor der Tür bekamen."],"casos.sub":["No siempre se rechaza la compra. En cinco de estos casos el cliente compró — pagando menos, y sabiendo exactamente qué estaba comprando.","Walking away isn't always the answer. In five of these cases the client bought — paying less, and knowing exactly what they were buying.","Nicht immer ist der Rückzug die Antwort. In fünf dieser Fälle kaufte der Kunde — günstiger und mit vollem Wissen."],
"casos.flag":["Precios en dólares · el precio final es el de cierre después de la inspección","Prices in US dollars · the final price is the closing price after the inspection","Preise in US-Dollar · der Endpreis ist der Abschlusspreis nach der Prüfung"],
"casos.out":["Resultado","Outcome","Ergebnis"],
"casos.q":["¿Valía la pena comprarlo?","Was it worth buying?","War der Kauf es wert?"],
"tb.modelo":["Modelo","Model","Modell"],
"tb.km":["Km","Km","Km"],
"tb.pi":["Precio inicial","Asking price","Angebotspreis"],
"tb.dec":["Decisión","Decision","Entscheidung"],
"tb.pf":["Precio final","Final price","Endpreis"],
"tb.rec":["Recomendaciones","Recommendations","Empfehlungen"],
"tb.obs":["Observaciones","Observations","Anmerkungen"],
"tb.kmw":["Km manipulado","Odometer tampered","Tacho manipuliert"],
"tb.hint":["Desliza la tabla para ver todas las columnas","Swipe the table to see every column","Tabelle wischen, um alle Spalten zu sehen"],
"dec.neg":["Compra con negociación","Buy after negotiating","Kauf nach Verhandlung"],
"dec.buy":["Compra","Buy","Kauf"],
"dec.rej":["Rechazar compra","Reject purchase","Kauf ablehnen"],
"reels.note":["Videos publicados en @predicar.pe — desliza para ver más","Videos published on @predicar.pe — swipe for more","Videos auf @predicar.pe — zum Blättern wischen"],
"nav.informe":["Ejemplo de informe","Sample report","Beispielbericht"],
"rep.k":["Informe de inspección precompra","Pre-purchase inspection report","Kaufprüfbericht"],
"rep.badge":["Caso real","Real case","Echter Fall"],
"rep.veh":["Vehículo","Vehicle","Fahrzeug"],
"rep.pages":["Entrega","Delivery","Übergabe"],
"rep.pagesv":["El mismo día","Same day","Am selben Tag"],
"rep.cta":["Ver el informe completo →","See the full report →","Ganzen Bericht ansehen →"],
"rep.note":["Informe real · datos del cliente y del vehículo omitidos","Real report · client and vehicle data removed","Echter Bericht · Kunden- und Fahrzeugdaten entfernt"],
"inf.eyebrow":["El entregable","The deliverable","Das Ergebnis"],
"inf.h2":["El informe que te da poder de negociación","The report that gives you negotiating power","Der Bericht, der dir Verhandlungsmacht gibt"],
"inf.sub":["Un informe real, completo: datos del vehículo, carrocería, motor, escáner OBD, prueba de manejo, análisis legal y la conclusión del inspector con la recomendación de compra.","A real, complete report: vehicle data, bodywork, engine, OBD scan, road test, legal analysis and the inspector's conclusion with a buying recommendation.","Ein echter, vollständiger Bericht: Fahrzeugdaten, Karosserie, Motor, OBD-Scan, Probefahrt, Rechtsprüfung und das Fazit des Gutachters mit Kaufempfehlung."],
"inf.flag":["Informe real de un peritaje · la extensión varía según el vehículo · datos del cliente omitidos","Real inspection report · length varies by vehicle · client data removed","Echter Prüfbericht · Umfang je Fahrzeug unterschiedlich · Kundendaten entfernt"],
"inf.close":["Cerrar","Close","Schließen"],
"inf.taller":["Con este informe vas a tu taller de confianza","Take this report to the workshop you trust","Mit diesem Bericht gehst du zu deiner Vertrauenswerkstatt"],
"inf.tallerp":["Llegas sabiendo exactamente qué hay que reparar y cuánto debería costar. Pides solo lo necesario y nadie te cobra de más.","You arrive knowing exactly what needs fixing and what it should cost. You ask only for what is needed, and nobody overcharges you.","Du weißt genau, was repariert werden muss und was es kosten sollte. Du beauftragst nur das Nötige — und niemand rechnet zu viel ab."],
"diff.b":["El escáner no sirve para ver si sale verde o rojo","A common service only tells you whether the car is good or bad","Ein üblicher Service sagt dir nur, ob das Auto gut oder schlecht ist"],
"diff.p":["Sirve para leer cómo se comporta el auto: qué módulo falla, cuándo y por qué. Un código borrado la víspera vuelve a aparecer manejando, y eso solo se ve escaneando antes y después de la prueba de manejo.","It is for reading how the car behaves: which module fails, when and why. A code cleared the day before comes back while driving, and that only shows if you scan before and after the road test.","Er zeigt, wie sich das Auto verhält: welches Steuergerät wann und warum ausfällt. Ein tags zuvor gelöschter Fehler kehrt während der Fahrt zurück — sichtbar nur, wenn man vor und nach der Probefahrt scannt."],
"nav.respaldo":["Respaldo","Who we are","Über uns"],
"bk.eyebrow":["¿Quién realiza el trabajo?","Who does the work?","Wer die Arbeit macht"],
"bk.h2":["Peritaje liderado por un ingeniero mecatrónico","Inspection led by a mechatronics engineer","Begutachtung unter Leitung eines Mechatronik-Ingenieurs"],
"bk.sub":["Quien revisa tu auto es quien diseñó y mantuvo vehículos de alta gama. Esa es la diferencia entre una opinión y un diagnóstico.","The person inspecting your car designed and maintained premium vehicles. That is the difference between an opinion and a diagnosis.","Wer dein Auto prüft, hat Premiumfahrzeuge konstruiert und gewartet. Das ist der Unterschied zwischen Meinung und Diagnose."],
"bk.role":["Ingeniero Mecatrónico","Mechatronics Engineer","Mechatronik-Ingenieur"],
"bk.org":["Fundador de Predicar · PUCP","Founder of Predicar · PUCP","Gründer von Predicar · PUCP"],
"bk.p":["No te hacemos revisar tres autos. La asesoría previa define cuál vale la pena inspeccionar y el peritaje confirma si se compra, se negocia o se descarta. Una sola inspección, una sola decisión.","We don't make you inspect three cars. The prior consult decides which one is worth inspecting, and the inspection confirms whether to buy, negotiate or walk. One inspection, one decision.","Wir lassen dich nicht drei Autos prüfen. Die Vorberatung bestimmt, welches sich lohnt, und das Gutachten klärt: kaufen, verhandeln oder aussteigen. Eine Prüfung, eine Entscheidung."],
"bk.brands":["Andrés trabajó en el diseño y la calidad de marcas como","Andrés worked on design and quality for brands such as","Andrés arbeitete an Design und Qualität für Marken wie"],
"vs.us":["auto revisado en promedio, porque primero definimos cuál revisar","car inspected on average, because we first decide which one to inspect","Auto im Schnitt geprüft, weil wir vorher klären, welches"],
"vs.themk":["Otras empresas","Other companies","Andere Anbieter"],
"vs.them":["autos revisados en promedio, y tú pagas cada inspección","cars inspected on average — and you pay for every inspection","Autos im Schnitt geprüft — und du zahlst jede Prüfung"],
"claim.b":["El único peritaje automotriz en Lima dirigido por un ingeniero mecatrónico","The only vehicle inspection service in Lima led by a mechatronics engineer","Der einzige Kfz-Gutachterdienst in Lima unter Leitung eines Mechatronik-Ingenieurs"],
"claim.p":["No solo revisamos autos: cuidamos tu inversión.","We don't just check cars — we protect your investment.","Wir prüfen nicht nur Autos — wir schützen deine Investition."],
"srv.who":["¿Para quién es?","Who is it for?","Für wen?"],
"casos.norej":["Sin compra","No purchase","Kein Kauf"],
"casos.listed":["precio de lista","list price","Listenpreis"],
"casos.b_neg":["Negoció","Negotiated","Verhandelt"],
"casos.b_rej":["Rechazó","Rejected","Abgelehnt"],
"casos.b_buy":["Compró","Bought","Gekauft"],
"sum.4":["Rango negociado por caso","Negotiated range per case","Verhandelte Spanne pro Fall"],
"sum.5":["Casos","Cases","Fälle"],

"cmp.eyebrow":["Qué incluye nuestro peritaje","What our inspection covers","Was unser Gutachten umfasst"],
"cmp.h2":["Peritaje completo y transparente, no una inspección básica","A complete, transparent inspection — not a basic check","Vollständige, transparente Prüfung statt Basis-Check"],
"cmp.sub":["La diferencia no está en mirar el auto. Está en medir, verificar los papeles y traducir cada hallazgo a un número.","The difference is not looking at the car. It is measuring it, checking the paperwork, and turning every finding into a number.","Der Unterschied liegt nicht im Ansehen, sondern im Messen, in der Papierprüfung und darin, jeden Befund in eine Zahl zu übersetzen."],
"cmp.col1":["Predicar","Predicar","Predicar"],
"cmp.col1s":["Peritaje completo","Full inspection","Vollgutachten"],
"cmp.col2":["Otras empresas","Other companies","Andere Anbieter"],
"cmp.col2s":["Inspección básica","Basic check","Basis-Check"],
"cmp.what":["Qué se revisa","What is checked","Was geprüft wird"],
"cmp.g1":["Inspección mecánica y estructural","Mechanical and structural inspection","Mechanische und strukturelle Prüfung"],
"cmp.g3":["Lo que nos diferencia y te hace ahorrar","What sets us apart and saves you money","Was uns unterscheidet und dir Geld spart"],"cmp.g2":["Análisis legal y documentario","Legal and document analysis","Rechts- und Dokumentenprüfung"],

"save.eyebrow":["Lo que te hace ahorrar","Where you save","Wo du sparst"],
"save.h2":["No solo revisamos autos: cuidamos tu inversión","We don't just check cars — we protect your investment","Wir prüfen nicht nur Autos — wir schützen deine Investition"],

"srv.eyebrow":["Servicios","Services","Leistungen"],
"srv.h2":["Cuatro servicios, un objetivo: tu mejor decisión","Four services, one goal: your best decision","Vier Leistungen, ein Ziel: deine beste Entscheidung"],
"srv.sub":["La mayoría de clientes empieza por la asesoría: definimos qué auto te conviene según tu uso real y tu presupuesto, antes de gastar en inspecciones.","Most clients start with the consult: we define which car fits your real use and budget before spending on inspections.","Die meisten starten mit der Beratung: Wir klären, welches Auto zu Nutzung und Budget passt, bevor Prüfkosten entstehen."],
"srv.gift":["Al contratar un peritaje, la asesoría previa va incluida — para que no termines revisando tres autos.","Book an inspection and the prior consult is included — so you don't end up checking three cars.","Bei Buchung eines Gutachtens ist die Beratung inklusive — damit du nicht drei Autos prüfen musst."],
"srv.book":["Reservar","Book","Buchen"],

"proc.eyebrow":["Cómo trabajamos","How we work","So arbeiten wir"],
"proc.h2":["De la reserva al informe, en un día","From booking to report, in one day","Von der Buchung zum Bericht an einem Tag"],

"book.eyebrow":["Reserva","Booking","Buchung"],
"book.h2":["Elige tu horario y págalo como te quede cómodo","Pick your slot and pay however suits you","Wähle deinen Termin und zahle, wie es dir passt"],
"book.sub":["Pagas desde Perú o desde el extranjero. Al confirmar, la cita queda en tu calendario y recibes la confirmación por WhatsApp.","Pay from Peru or from abroad. On confirmation the appointment lands in your calendar and you get a WhatsApp confirmation.","Zahle aus Peru oder aus dem Ausland. Nach Bestätigung landet der Termin in deinem Kalender, samt WhatsApp-Bestätigung."],
"pay.h":["Datos para el pago","Payment details","Zahlungsdaten"],"pay.nota":["La reserva se abona por adelantado. Sube el comprobante en el formulario y el horario queda bloqueado a tu nombre.","The booking is paid in advance. Upload the receipt in the form and the slot is locked under your name.","Die Buchung wird im Voraus bezahlt. Lade den Beleg im Formular hoch und der Termin wird auf deinen Namen reserviert."],"pay.tit":["Titular","Account holder","Kontoinhaber"],"pay.bcp":["BCP · cuenta en dólares","BCP · USD account","BCP · USD-Konto"],"pay.cci":["CCI","CCI (interbank)","CCI (Interbank)"],"pay.plin":["Plin · Yape","Plin · Yape","Plin · Yape"],"pay.tc":["Tipo de cambio","Exchange rate","Wechselkurs"],"pay.copiar":["Copiar","Copy","Kopieren"],"pay.copiado":["Copiado","Copied","Kopiert"],"f.srv":["Servicio","Service","Leistung"],
"f.fecha":["Fecha","Date","Datum"],
"f.hora":["Hora disponible","Available time","Verfügbare Zeit"],
"f.pago":["Método de pago","Payment method","Zahlungsart"],
"f.nom":["Nombre completo","Full name","Vollständiger Name"],
"f.tel":["WhatsApp","WhatsApp","WhatsApp"],
"f.mail":["Correo","Email","E-Mail"],
"f.dir":["Dirección donde está el vehículo","Address where the vehicle is","Adresse des Fahrzeugs"],
"f.obs":["Algo que debamos saber","Anything we should know","Was wir wissen sollten"],
"f.submit":["Confirmar mi cita","Confirm my appointment","Termin bestätigen"],
"f.loading":["Buscando horarios…","Loading times…","Zeiten werden geladen …"],
"f.errload":["No pudimos cargar los horarios. Recarga la página o escríbenos por WhatsApp.","We could not load the times. Reload the page or message us on WhatsApp.","Zeiten konnten nicht geladen werden. Seite neu laden oder per WhatsApp schreiben."],
"f.errtaken":["Ese horario acaba de ser reservado por otra persona. Elige otro, por favor.","That slot was just booked by someone else. Please pick another one.","Dieser Termin wurde gerade vergeben. Bitte einen anderen wählen."],
"f.errbig":["El comprobante pesa más de 4 MB. Sube una imagen más liviana.","The receipt is over 4 MB. Please upload a lighter image.","Der Beleg ist größer als 4 MB. Bitte kleineres Bild hochladen."],
"f.voucher":["Comprobante de pago","Payment receipt","Zahlungsbeleg"],
"f.dur":["La inspección toma entre 45 minutos y 1 hora.","The inspection takes 45 minutes to 1 hour.","Die Prüfung dauert 45 Minuten bis 1 Stunde."],
"f.blocked":["No tenemos horarios disponibles. Elige otro día.","We don't work that date. Pick another day.","An diesem Datum arbeiten wir nicht. Bitte anderen Tag wählen."],
"f.nofree":["No quedan horarios disponibles. Elige otra fecha.","No slots available. Pick another date.","Keine Termine verfügbar. Bitte anderes Datum wählen."],
"f.errslot":["Elige una fecha y un horario disponible.","Pick a date and an available time.","Bitte Datum und freie Uhrzeit wählen."],
"f.errdata":["Necesitamos tu nombre y tu correo para confirmarte la cita.","We need your name and email to confirm the appointment.","Wir brauchen Name und E-Mail, um den Termin zu bestätigen."],
"f.errvoucher":["Sube el comprobante de pago para reservar el horario.","Upload the payment receipt to reserve the slot.","Zahlungsbeleg hochladen, um den Termin zu reservieren."],
"f.errsave":["No pudimos registrar la cita. Escríbenos por WhatsApp y la coordinamos.","We could not save the appointment. Message us on WhatsApp and we'll sort it out.","Der Termin konnte nicht gespeichert werden. Schreib uns per WhatsApp."],
"f.sending":["Registrando tu cita…","Saving your appointment…","Termin wird gespeichert …"],
"f.ok":["Cita confirmada: {s} el {f} a las {h}. Te enviamos la confirmación a {m} y ese horario ya quedó reservado.","Appointment confirmed: {s} on {f} at {h}. Confirmation sent to {m} and that slot is now reserved.","Termin bestätigt: {s} am {f} um {h}. Bestätigung an {m} gesendet, der Termin ist reserviert."],
"f.demo":["Vista previa: aquí se reservaría {s} el {f} a las {h}. En el sitio publicado en tu dominio esto guarda la cita, envía el correo y bloquea el horario.","Preview: this would book {s} on {f} at {h}. On your published domain this saves the appointment, sends the email and blocks the slot.","Vorschau: hier würde {s} am {f} um {h} gebucht. Auf deiner Domain speichert das den Termin, sendet die E-Mail und sperrt die Zeit."],
"f.note":["Al confirmar, el horario queda reservado y recibes el correo de confirmación.","On confirmation the slot is reserved and you receive the confirmation email.","Nach der Bestätigung ist der Termin reserviert und du erhältst die Bestätigungsmail."],

"auto.h3":["Qué pasa al confirmar","What happens on confirmation","Was nach der Bestätigung passiert"],
"auto.p":["Todo automático, sin coordinar por chat.","All automatic — no back-and-forth by chat.","Alles automatisch — kein Hin und Her im Chat."],
"cov.h3":["Cobertura en Lima","Coverage in Lima","Abdeckung in Lima"],
"cov.wa":["Estoy fuera de esa zona","I'm outside that area","Ich bin außerhalb des Gebiets"],

"sys.h2":["Acceso al sistema","System login","System-Login"],
"sys.sub":["Panel de Predicar y de los talleres asociados","Panel for Predicar and partner workshops","Portal für Predicar und Partnerwerkstätten"],
"sys.admin":["Predicar · Admin","Predicar · Admin","Predicar · Admin"],
"sys.taller":["Taller asociado","Partner workshop","Partnerwerkstatt"],
"sys.user":["Usuario / correo","User / email","Benutzer / E-Mail"],
"sys.pass":["Contraseña","Password","Passwort"],
"sys.enter":["Ingresar","Sign in","Anmelden"],
"sys.hint":["Prototipo — pulsa Ingresar para ver el panel","Prototype — press Sign in to see the panel","Prototyp — auf Anmelden klicken"],
"dash.eyebrow":["Panel interno","Internal panel","Internes Panel"],
"dash.h2":["Indicadores del negocio","Business indicators","Geschäftskennzahlen"],
"dash.logout":["Cerrar sesión","Sign out","Abmelden"],
"dash.chart":["Servicios por tipo","Services by type","Leistungen nach Typ"],
"dash.chartcap":["Agosto 2026 · unidades y facturación","August 2026 · units and revenue","August 2026 · Anzahl und Umsatz"],
"dash.exp":["Registro de gastos","Expense log","Ausgabenübersicht"],
"dash.expcap":["Agosto 2026 · datos de ejemplo","August 2026 · example data","August 2026 · Beispieldaten"],
"dash.concept":["Concepto","Item","Posten"],
"road.h3":["En construcción","In progress","In Arbeit"],

"foot.tag":["Peritaje e inspección vehicular en Lima. No solo revisamos autos: cuidamos tu inversión.","Vehicle inspection and appraisal in Lima. We don't just check cars — we protect your investment.","Fahrzeugprüfung und Begutachtung in Lima. Wir prüfen nicht nur Autos — wir schützen deine Investition."],
"foot.srv":["Servicios","Services","Leistungen"],
"foot.s1":["Asesoría 30 min","30-min consult","30-Min-Beratung"],
"foot.s2":["Peritaje automotriz","Vehicle inspection","Fahrzeuggutachten"],
"foot.s3":["Búsqueda vehicular","Car sourcing","Fahrzeugsuche"],
"foot.pay":["Pagos","Payments","Zahlungen"],
"foot.contact":["Contacto","Contact","Kontakt"],
"foot.proto":["Prototipo — contenido de ejemplo","Prototype — example content","Prototyp — Beispielinhalt"]
};

function t(k){ var v = T[k]; return v ? v[L] : k; }

/* ---------- data ---------- */
